config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, except: :index
  resources :profile
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :age,             present: false
  validates :sex,             present: false
  validates :height,          present: false
  validates :weight,          present: false
  validates :activity_amount, present: false

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :profile, dependent: :destroy, class_name: Profile

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end

  def show
  end

  def new
    @profile = profile.new
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(name: session_params[:name])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = "ログインしました。"
      redirect_to root_path
    else
      flash[:danger] = "ログインできませんでした。"
      render :new
    end
  end

  def destroy
    reset_session
    flash[:success] = "ログアウトしました。"
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:name, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "ユーザー「#{@user.name}」を登録しました。"
      redirect_to users_path(@user)
    else
      flash[:danger] = "「#{@user.name}」はすでに使用されています。"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Calme
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-dark.bg-dark
      .navbar-brand Calme
      
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - flash.each do |type, message|
        div class="alert alert-#{type}"
          = message
      = yield
      .navbar-brand Calme
      
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - flash.each do |type, message|
        div class="alert alert-#{type}"
          = message
      = yield

app/views/static_pages/home.html.slim
h1 Calme へようこそ

= link_to "ユーザー登録", new_user_path, class: "btn btn-primary"

app/views/users/index.html.slim
h1 Users#index

table.table
  thead.thead-dark
    tr
      th scope="col" id
      th scope="col" name
      th
  tbody
    - @users.each do |user|
      tr
        th scope="row" = user.id
        td = user.name
        td = link_to "詳細", user_path(user), class: "btn btn-primary"

app/views/users/new.html.slim
h1 ユーザー登録
= form_with model: @user, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/users/show.html.slim
h1 User#show

table.table
  thead
    tr
      th id
      th name
      th created_at
  tbody
    tr
      td = @user.id
      td = @user.name
      td = @user.created_at